version: '2.1'
services:
  web:
    build: .
    ports:
     - "5000:5000"
    volumes:
     - .:/code
    healthcheck:
      test: "exit 0"
  redis:
    image: "redis:alpine"
    healthcheck:
      test: "exit 0"
