version: '2.1'
services:
  web:
    build: .
    ports:
     - "5000:5000"
    volumes:
     - .:/code
    healthcheck:
      test: ["CMD", "exit 0"]
      interval: 1m30s
      timeout: 10s
      retries: 3
  redis:
    image: "redis:alpine"
